FROM postgres:18.3

ARG DB_USER=myuser
ARG DB_PASSWORD=mypassword
ARG DB_NAME=TrainingsOrganizer

ENV POSTGRES_USER=$DB_USER
ENV POSTGRES_PASSWORD=$DB_PASSWORD
ENV POSTGRES_DB=$DB_NAME

COPY schema.sql /docker-entrypoint-initdb.d/01_schema.sql
COPY sample_data.sql /docker-entrypoint-initdb.d/02_sample_data.sql

EXPOSE 5432